version: '3'

services:
  db:
    image: mysql:5.7
    container_name: tyrell-db
    environment:
      MYSQL_ROOT_PASSWORD: abcde12345
      MYSQL_DATABASE: programming_test
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - tyrell-db-volume:/var/lib/mysql/
    ports:
      - "3306:3306"
    networks:
      - tyrell-net

  programming-backend:
    container_name: programming-backend
    build:
      context: ./A-Programming/card-backend/
      args:
        DB_HOST: tyrell-db
        DB_NAME: programming_test
        DB_USER: user
        DB_PASS: user123
    depends_on:
      - db
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
    networks:
      - tyrell-net

  programming-frontend:
    container_name: programming-frontend
    build:
      args:
        API_BASE_URL: http://localhost:8080/
      context: ./A-Programming/card-frontend/
    ports:
      - "80:3000"
    networks:
      - tyrell-net

  sql-improvement:
    container_name: sql-improvement
    build:
      context: ./B-SQL_Improvement
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - tyrell-net

# Networks
networks:
  tyrell-net:
    driver: bridge

# Volumes
volumes:
  tyrell-db-volume:
    driver: local
