version: '3'

services:
  db:
    image: mysql:5.7
    container_name: tyrell-db
    environment:
      MYSQL_ROOT_PASSWORD: abcde12345
      MYSQL_DATABASE: programming_test
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - tyrell-db-volume:/var/lib/mysql/
    ports:
      - "3306:3306"
    networks:
      - tyrell-net

  programming-backend:
    image: php:apache
    container_name: programming-backend
    build:
      context: ./A-Programming/card-backend/
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - ./A-Programming/card-backend/:/var/www/html/
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
    networks:
      - tyrell-net

# Networks
networks:
  tyrell-net:
    driver: bridge

# Volumes
volumes:
  tyrell-db-volume:
    driver: local
